const initialProducts=[
{id:1,name:'Classic Cotton T-Shirt',category:'Apparel',price:799,status:'Published',description:'Breathable cotton t-shirt for everyday casual wear.',seoTitle:'Classic Cotton T-Shirt | ShopOps',meta:'Shop a breathable classic cotton t-shirt for everyday comfort.',alt:'White cotton t-shirt on a neutral background',tags:'cotton, casual, apparel'},
{id:2,name:'Minimal Desk Lamp',category:'Home Decor',price:1499,status:'Review',description:'',seoTitle:'',meta:'',alt:'',tags:'lamp, desk'},
{id:3,name:'Insulated Travel Bottle',category:'Accessories',price:999,status:'Draft',description:'Double-wall insulated bottle for hot and cold beverages.',seoTitle:'Travel Bottle',meta:'',alt:'Insulated steel travel bottle',tags:''},
{id:4,name:'Wireless Keyboard',category:'Electronics',price:2199,status:'Published',description:'Compact wireless keyboard with a comfortable typing layout.',seoTitle:'Wireless Keyboard | ShopOps',meta:'Compact wireless keyboard for work and study.',alt:'',tags:'keyboard, wireless, office'}
];
let products=JSON.parse(localStorage.getItem('shopops-products')||'null')||initialProducts;const $=id=>document.getElementById(id);
function save(){localStorage.setItem('shopops-products',JSON.stringify(products));render()}
function quality(p){return [p.name,p.description,p.seoTitle,p.meta,p.alt,p.tags].filter(v=>String(v||'').trim()).length/6}
function render(){const q=$('searchInput').value.toLowerCase(),status=$('statusFilter').value;const filtered=products.filter(p=>(p.name+' '+p.category).toLowerCase().includes(q)&&(status==='all'||p.status===status));$('productTable').innerHTML=filtered.map(p=>`<tr><td>${escapeHtml(p.name)}</td><td>${escapeHtml(p.category)}</td><td>₹${Number(p.price).toLocaleString('en-IN')}</td><td><span class="pill ${p.status.toLowerCase()}">${p.status}</span></td><td class="${p.seoTitle&&p.meta?'seo-good':'seo-bad'}">${p.seoTitle&&p.meta?'Ready':'Needs work'}</td><td>${Math.round(quality(p)*100)}%</td><td><button class="table-action" data-edit="${p.id}">Edit</button></td></tr>`).join('');$('emptyState').classList.toggle('hidden',filtered.length>0);$('totalProducts').textContent=products.length;$('publishedProducts').textContent=products.filter(p=>p.status==='Published').length;$('seoIssues').textContent=products.filter(p=>!p.seoTitle||!p.meta).length;$('qualityScore').textContent=Math.round(products.reduce((s,p)=>s+quality(p),0)/Math.max(products.length,1)*100)+'%';$('metaIssues').textContent=products.filter(p=>!p.meta).length;$('descriptionIssues').textContent=products.filter(p=>(p.description||'').length<35).length;$('altIssues').textContent=products.filter(p=>!p.alt).length;$('tagIssues').textContent=products.filter(p=>!p.tags).length;}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function openForm(p=null){$('dialogTitle').textContent=p?'Edit product':'Add product';$('productId').value=p?.id||'';$('productName').value=p?.name||'';$('productCategory').value=p?.category||'';$('productPrice').value=p?.price||'';$('productDescription').value=p?.description||'';$('productStatus').value=p?.status||'Draft';$('productSeoTitle').value=p?.seoTitle||'';$('productMeta').value=p?.meta||'';$('productAlt').value=p?.alt||'';$('productTags').value=p?.tags||'';$('productDialog').showModal()}
$('addProductBtn').addEventListener('click',()=>openForm());$('productTable').addEventListener('click',e=>{const id=e.target.dataset.edit;if(id)openForm(products.find(p=>p.id===Number(id)))});$('productForm').addEventListener('submit',e=>{e.preventDefault();const id=Number($('productId').value);const p={id:id||Date.now(),name:$('productName').value.trim(),category:$('productCategory').value.trim(),price:Number($('productPrice').value),status:$('productStatus').value,description:$('productDescription').value.trim(),seoTitle:$('productSeoTitle').value.trim(),meta:$('productMeta').value.trim(),alt:$('productAlt').value.trim(),tags:$('productTags').value.trim()};products=id?products.map(x=>x.id===id?p:x):[p,...products];$('productDialog').close();save()});$('searchInput').addEventListener('input',render);$('statusFilter').addEventListener('change',render);$('themeToggle').addEventListener('click',()=>document.body.classList.toggle('dark'));$('checklist').addEventListener('change',()=>{const all=[...document.querySelectorAll('#checklist input')],done=all.filter(x=>x.checked).length;$('checkProgress').style.width=done/all.length*100+'%';$('checkSummary').textContent=`${done} of ${all.length} checks complete`});$('exportBtn').addEventListener('click',()=>{const headers=['Name','Category','Price','Status','Description','SEO Title','Meta Description','Image Alt Text','Tags'];const rows=products.map(p=>[p.name,p.category,p.price,p.status,p.description,p.seoTitle,p.meta,p.alt,p.tags]);const csv=[headers,...rows].map(row=>row.map(v=>'"'+String(v??'').replace(/"/g,'""')+'"').join(',')).join('\n');const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([csv],{type:'text/csv'}));a.download='shopops-product-catalogue.csv';a.click();URL.revokeObjectURL(a.href)});render();
